backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"

display_url: https://tedxparisdauphine.com

collections:
  - name: "videos" # Used in routes, e.g., /admin/collections/blog
    label: "Videos" # Used in the UI
    folder: "_videos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Social media image", name: "image", widget: "image"}
      - label: "Theme"
        name: "theme"
        widget: "object"
        fields:
          - {label: "Theme title", name: "title", widget: "string"}
          - {label: "Theme description", name: "description", widget: "text"}
      - {label: "Banner", name: "banner", widget: "image"}
      - label: "Talks"
        name: "talks"
        widget: "list"
        fields:
          - {label: "Speaker first name", name: speaker-first-name, widget: string}
          - {label: "Speaker last name", name: speaker-last-name, widget: string}
          - {label: "Talk title", name: title, widget: string}
          - {label: "Talk description", name: description, widget: text}
          - {label: "YouTube ID", name: description, widget: youtube-id}

  - label: "Data"
    name: "data"
    files:
      - label: "Partners"
        name: "partners"
        file: "_data/partners.yml"
        fields:
          - label: Partners
            name: partners
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Logo, name: logo, widget: image}
              - {label: Website, name: website, widget: string}
              - {label: Description, name: description, widget: text}
      - label: "Speakers"
        name: "speakers"
        file: "_data/speakers.yml"
        fields:
          - label: Speakers
            name: speakers
            widget: list
            fields:
              - {label: 'First name', name: first-name, widget: string}
              - {label: 'Last name', name: last-name, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Picture, name: picture, widget: image}
      - label: "Teams"
        name: "teams"
        file: "_data/teams.yml"
        fields:
          - label: Teams
            name: teams
            widget: list
            fields:
              - {label: Year, name: year, widget: string}
              - {label: Members, name: members, widget: text}